apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-pod-identity-demo-4
  region: ap-southeast-1
  version: "1.30"

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: eks-pod-identity-agent
    
managedNodeGroups:
  - name: eks-shared-demo-mng
    instanceType: t3a.medium
    privateNetworking: true
    minSize: 2
    desiredCapacity: 2
    maxSize: 5
